#pragma once

#include "Base/Macros.h"
#include "Base/FourCID.h"
#include <cstddef>

//----------------------------------------------------------------------------------------------------------------------
// Utility stuff relating for handling 3DO 'stream' files that have been generated by the 3DO SDK tool 'weaver'.
// Streams files consist of a series of streams that have been broken up into chunks, and packed into one file.
// The chunks are interleaved so they can be read together in tandem, for efficient streaming of mixed content off a CD-ROM.
//
// In 3DO Doom these stream files are just used to contain audio and video data for the intro movies.
//----------------------------------------------------------------------------------------------------------------------
BEGIN_NAMESPACE(ChunkedStreamFileUtils)

//----------------------------------------------------------------------------------------------------------------------
// Extracts the entire data for the specified sub stream in the given stream file.
// The data and it's size are returned in the given input variables.
// Returns 'false' on failure to read the stream.
//----------------------------------------------------------------------------------------------------------------------
bool getSubStreamData(
    const std::byte* const pStreamFileData,
    const uint32_t streamFileSize,
    const FourCID subStreamId,
    std::byte*& pSubStreamDataOut,
    uint32_t& subStreamSizeOut
) noexcept;

END_NAMESPACE(ChunkedStreamFileUtils)
